### ISSUE TITLE
Error trying upload a blob 

### ISSUE THREAD

**Issue by leandro-leroymerlin** [adobe/aem-upload#55]
### Expected Behaviour
Upload an asset using blob

### Actual Behaviour
TypeError: Expected a string, got undefinedIn *filePath*

#### Platform and Version
Node 12.16.3
"@adobe/aem-upload": "^1.1.4"

#### Sample Code that illustrates the problem
```
const buffer = Buffer.from(b64Data, 'base64');
const size = buffer.byteLength;
const arrayBufffer = Array.prototype.slice.call(buffer);

const uploadFiles = [
        {
            fileSize: size,
            fileName: 'prueba1.png',
            blob: [...arrayBuffer]
        },
    ];

    const upload = new DirectBinary.DirectBinaryUpload();
    const options = new DirectBinary.DirectBinaryUploadOptions()
        .withUrl(targetUrl)
        .withUploadFiles(uploadFiles)
```

#### Logs taken while reproducing problem
```
TypeError: Expected a string, got undefined
    at module.exports (C:\Users\Leandro\Desktop\ham\experience-manager-cloud-service\node_modules\file-url\index.js:6:9)
    at C:\Users\Leandro\Desktop\ham\experience-manager-cloud-service\node_modules\@adobe\httptransfer\es2015\aem\aemupload.js:213:25
    at Generator.next (<anonymous>)
    at resume (C:\Users\Leandro\Desktop\ham\experience-manager-cloud-service\node_modules\@adobe\httptransfer\es2015\aem\aemupload.js:114:362)
    at C:\Users\Leandro\Desktop\ham\experience-manager-cloud-service\node_modules\@adobe\httptransfer\es2015\aem\aemupload.js:114:281
    at new Promise (<anonymous>)
    at _AsyncGenerator.send [as _invoke] (C:\Users\Leandro\Desktop\ham\experience-manager-cloud-service\node_modules\@adobe\httptransfer\es2015\aem\aemupload.js:114:83)
    at _AsyncGenerator.next (C:\Users\Leandro\Desktop\ham\experience-manager-cloud-service\node_modules\@adobe\httptransfer\es2015\aem\aemupload.js:118:63)
    at C:\Users\Leandro\Desktop\ham\experience-manager-cloud-service\node_modules\@adobe\httptransfer\es2015\functions\filterfailedassets.js:57:121
    at Generator.next (<anonymous>)
```

**Comment by mfrisbey** [comment]
The `TypeError` itself has been fixed with #61.

However, the README has also been updated to specify that the only tested and supported value for the `blob` option is that of an HTML `<input type="file" />`. We don't officially support the `blob` option through Node.JS. You're welcome to experiment to see if you can get it to work, but the recommendation is to use the `filePath` option when running Node.JS.
